dependencies {
	implementation project(":domain")
	implementation project(":application")

	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-json'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework:spring-web'
	implementation 'org.springframework.security:spring-security-oauth2-client'
	implementation 'org.springframework.security:spring-security-oauth2-core'
	implementation 'org.springframework.session:spring-session-core'
	implementation 'org.apache.httpcomponents.client5:httpclient5'
	implementation 'io.micrometer:micrometer-core'
	implementation 'io.github.resilience4j:resilience4j-circuitbreaker:2.3.0'
	implementation 'io.github.resilience4j:resilience4j-micrometer:2.3.0'
	implementation 'io.github.resilience4j:resilience4j-timelimiter:2.3.0'

	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}
