apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - --entryPoints.web.forwardedHeaders.insecure=false
      - --entryPoints.websecure.forwardedHeaders.insecure=false
