CREATE TABLE payment_settlements (
    id BIGINT NOT NULL AUTO_INCREMENT,
    transaction_key VARCHAR(64) NOT NULL,
    payment_key VARCHAR(200) NOT NULL,
    order_id_external VARCHAR(64) NULL,
    payment_method VARCHAR(30) NULL,
    amount BIGINT NOT NULL,
    fee_amount BIGINT NOT NULL,
    supply_amount BIGINT NOT NULL,
    vat BIGINT NOT NULL,
    pay_out_amount BIGINT NOT NULL,
    approved_at VARCHAR(40) NULL,
    sold_date DATE NOT NULL,
    paid_out_date DATE NULL,
    cancel_transaction BOOLEAN NOT NULL,
    reconciliation_status VARCHAR(30) NOT NULL,
    reconciliation_reason VARCHAR(500) NULL,
    fetched_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_payment_settlement_transaction_key (transaction_key),
    KEY idx_payment_settlement_issue (reconciliation_status, sold_date, id)
);
