export type ErrorCode =
  | "INVALID_INPUT"
  | "PHONE_VERIFICATION_FAILED"
  | "UNAUTHORIZED"
  | "INVALID_CREDENTIALS"
  | "SOCIAL_LOGIN_FAILED"
  | "SOCIAL_ACCOUNT_LINK_REQUIRED"
  | "EMAIL_ALREADY_EXISTS"
  | "NOT_FOUND"
  | "ALREADY_REFUNDED"
  | "INVENTORY_NOT_ENOUGH"
  | "CAPACITY_EXCEEDED"
  | "DUPLICATE_BOOKING"
  | "SLOT_NOT_AVAILABLE"
  | "BOOKING_CONFLICT"
  | "CONFLICT"
  | "TOO_MANY_REQUESTS"
  | "REFUND_NOT_ALLOWED"
  | "PRODUCTION_REFUND_NOT_ALLOWED"
  | "CHANGE_NOT_ALLOWED"
  | "PASS_EXPIRED"
  | "PASS_CREDIT_INSUFFICIENT"
  | "PAYMENT_METHOD_NOT_ALLOWED"
  | "INTERNAL_ERROR";

export interface ErrorResponse {
  code: ErrorCode;
  message: string;
  requestId?: string;
}
