import {
  index,
  layout,
  route,
  type RouteConfig,
} from "@react-router/dev/routes";

export default [
  route("healthz", "./routes/resource/health.ts"),
  route("robots.txt", "./routes/resource/robots.ts"),
  route("sitemap.xml", "./routes/resource/sitemap.ts"),

  index("./routes/public/home.tsx"),
  route("notices/:id", "./routes/public/notice-detail.tsx"),
  route("events", "./routes/public/events.tsx"),
  route("events/:id", "./routes/public/event-detail.tsx"),
  route("products", "./routes/public/products.tsx"),
  route("products/:id", "./routes/public/product-detail.tsx"),
  route("classes", "./routes/public/classes.tsx"),
  route("classes/:id", "./routes/public/class-detail.tsx"),
  route("group-classes", "./routes/public/group-classes.tsx"),
  route("terms/:version?", "./routes/public/terms.tsx"),
  route("privacy/:version?", "./routes/public/privacy.tsx"),
  route("business-info", "./routes/public/business-info.tsx"),

  layout("./routes/client-only-layout.tsx", [
    route("bookings/new", "./routes/client/booking-create.tsx"),
    route("guest", "./routes/client/guest-lookup.tsx"),
    route("guest/payments/:orderId", "./routes/client/guest-payment-status.tsx"),
    route("guest/bookings", "./routes/client/booking-manage.tsx"),
    route("passes/purchase", "./routes/client/pass-purchase.tsx"),
    route("cart", "./routes/client/cart.tsx"),
    route("orders/new", "./routes/client/order-create.tsx"),
    route("guest/orders", "./routes/client/order-detail.tsx"),
    route("my", "./routes/client/my.tsx"),
    route("my/orders", "./routes/client/my-orders.tsx"),
    route("my/bookings/:id", "./routes/client/my-booking-detail.tsx"),
    route("my/bookings", "./routes/client/my-bookings.tsx"),
    route("my/orders/:id", "./routes/client/my-order-detail.tsx"),
    route("my/passes", "./routes/client/my-passes.tsx"),
    route("my/benefits", "./routes/client/my-benefits.tsx"),
    route("my/inquiries", "./routes/client/my-inquiries.tsx"),
    route("my/inquiries/new", "./routes/client/my-inquiry-create.tsx"),
    route("my/reviews", "./routes/client/my-reviews.tsx"),
    route("auth/callback", "./routes/client/social-callback.tsx"),
    route("login", "./routes/client/login.tsx"),
    route("signup", "./routes/client/signup.tsx"),
    route("forgot-password", "./routes/client/forgot-password.tsx"),
    route("admin", "./routes/client/admin.tsx"),
    route("payments/success", "./routes/client/payment-success.tsx"),
    route("payments/fail", "./routes/client/payment-fail.tsx"),
  ]),

  route("*", "./routes/not-found.tsx"),
] satisfies RouteConfig;
