apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-media
  labels:
    app.kubernetes.io/name: app-media
    app.kubernetes.io/part-of: happygallery
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 5Gi
