apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: happygallery
resources:
  - namespace.yaml
  - storage-class.yaml
  - app-config.yaml
  - mysql.yaml
  - redis.yaml
  - app.yaml
  - frontend.yaml
  - prometheus.yaml
  - alertmanager.yaml
  - ingress.yaml
  - network-policy.yaml
