package com.personal.happygallery.domain.order;

public enum SmartStoreOrderAction {
    INVENTORY_RESOLVED,
    ORDER_CONFIRMED,
    ORDER_DISPATCHED,
    ORDER_DELAYED,
    CANCEL_APPROVED,
    RETURN_APPROVED,
    RETURN_REJECTED,
    RETURN_HELD,
    RETURN_HOLD_RELEASED,
    RETURN_REQUESTED,
    EXCHANGE_DISPATCHED,
    EXCHANGE_COLLECTION_COMPLETED,
    EXCHANGE_REJECTED,
    EXCHANGE_HELD,
    EXCHANGE_HOLD_RELEASED,
    CANCEL_REQUESTED
}
